name: cloudinary_flutter
description: Cloudinary is a cloud service that offers a solution to a web application's entire image management pipeline
version: 0.0.2
homepage: https://www.cloudinary.com
repository: https://github.com/cloudinary/cloudinary_flutter

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  video_player: ^2.4.8
  cloudinary_dart: ^0.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^2.0.1
  test: ^1.21.4